import React, { useState, useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';
import { MessageSquare, X, Send, Bot, User, Loader2 } from 'lucide-react';

const pageContexts = {
  '/dashboard': {
    title: 'Executive Dashboard',
    greeting: 'Hi! I am your SolarIntel Assistant. I can help you understand the executive metrics on this dashboard.',
    questions: [
      {
        q: 'What does this dashboard show?',
        a: 'This is the Executive Dashboard. It provides a high-level summary of India\'s solar market, aggregating 81+ GW of capacity across all states. You can toggle between Capacity and Revenue views, export reports, and see carbon offset estimates.'
      },
      {
        q: 'How is Total Revenue calculated?',
        a: 'Total Revenue is mathematically estimated using our backend pipeline. It assumes a 70/30 split between Utility-Scale and Rooftop installations, calculating the capital expenditure (CapEx) generated by the installed KW footprint.'
      },
      {
        q: 'Who are the Top Performers?',
        a: 'The Top Performers list at the bottom ranks states based on their total cumulative solar capacity. Currently, Rajasthan and Gujarat dominate the market due to massive land availability and favorable state policies.'
      },
      {
        q: 'How frequently is the dashboard updated?',
        a: 'The dashboard metrics are synchronized regularly with our backend pipeline, ensuring that capacity and revenue estimates reflect the most recent data available.'
      }
    ]
  },
  '/overview': {
    title: 'Project Overview',
    greeting: 'Welcome to the presentation! Let me know if you need me to summarize any of these architecture points.',
    questions: [
      { q: 'What is the ML architecture?', a: 'We use a Python FastAPI microservice running Scikit-Learn Polynomial Regression to map exponential solar growth.' },
      { q: 'How large is the dataset?', a: 'We have over 500+ granular records across 10 years, tracking 36 states and union territories.' }
    ]
  },
  '/analytics': {
    title: 'Detailed Analytics',
    greeting: 'Welcome to the Analytics Engine! Ask me about any of our 6 analysis models (CAGR, YoY, Capacity across State and City views).',
    questions: [
      {
        q: 'What does State-Wise CAGR show?',
        a: 'State-Wise CAGR (Compound Annual Growth Rate) shows the smoothed 10-year annualized growth rate of solar capacity across different states, highlighting regions with consistent, long-term market expansion.'
      },
      {
        q: 'What is State-Wise YoY Momentum?',
        a: 'This measures the percentage change in capacity strictly between the last two recorded years for states. It acts as a short-term volatility indicator to spot immediate policy or investment impacts.'
      },
      {
        q: 'What is State-Wise Total Capacity?',
        a: 'It represents the absolute total sum of all solar infrastructure installed in each state, highlighting the absolute market leaders by pure physical volume.'
      },
      {
        q: 'What does City-Wise CAGR show?',
        a: 'By evaluating specific solar parks and cities, City-Wise CAGR shows long-term growth trends at a hyper-local level, allowing you to pinpoint sustained micro-market expansion.'
      },
      {
        q: 'What is City-Wise YoY Momentum?',
        a: 'This tracks immediate, short-term percentage growth jumps in specific cities or parks. It is extremely useful for finding new localized mega-projects that recently came online.'
      },
      {
        q: 'What is City-Wise Total Capacity?',
        a: 'It displays the total volume of solar installations at the individual city or solar park level, showing exactly which specific local regions dominate the physical infrastructure.'
      }
    ]
  },
  '/geo': {
    title: 'Geo Analytics',
    greeting: 'Hello! I can guide you through the interactive Map visualizations.',
    questions: [
      {
        q: 'What do the circles on the map mean?',
        a: 'Each circle represents a state. The size of the circle corresponds to the state\'s Total Solar Capacity (larger circle = more capacity). You can hover over them to see exact figures.'
      },
      {
        q: 'How does the Heatmap work?',
        a: 'The heatmap color-codes states based on density. By visualizing where solar infrastructure is highly concentrated (like the Western corridor), you can identify "dark zones" that are ripe for future investment.'
      },
      {
        q: 'Does geography impact solar potential?',
        a: 'Absolutely. States closer to the equator and those with expansive, arid landmasses (like Rajasthan) naturally receive higher direct normal irradiance (DNI), heavily influencing their aggregate capacity.'
      }
    ]
  },
  '/forecast': {
    title: 'ML Forecasting Engine',
    greeting: 'Welcome to the Forecasting Engine! Ask me about how our ML models predict the future.',
    questions: [
      {
        q: 'How accurate is the prediction?',
        a: 'The prediction relies on historical capacity data fed into our Scikit-Learn pipeline. Currently, we utilize a robust Linear Regression model with confidence intervals. While highly accurate for linear trends, massive sudden policy shifts can cause variances.'
      },
      {
        q: 'What do the shaded areas on the graph mean?',
        a: 'The shaded blue area represents the Confidence Interval. It shows the mathematically probable upper and lower bounds of the prediction. The solid line is the exact projected target.'
      },
      {
        q: 'Which machine learning models are used?',
        a: 'Currently, the engine relies on a customized Linear Regression pipeline built on Scikit-Learn, optimized for time-series capacity forecasting over a multi-year horizon.'
      }
    ]
  },
  '/sales': {
    title: 'Sales Intelligence',
    greeting: 'Hi! Let me explain the Market Share dynamics on this page.',
    questions: [
      {
        q: 'What insights does Market Share provide?',
        a: 'Market Share shows how the national solar pie is divided among the states. By selecting different years from the dropdown, you can watch how early adopters (like Gujarat) eventually lost partial market share to rapidly emerging states (like Karnataka).'
      },
      {
        q: 'Why did early adopters lose market share?',
        a: 'As the overall national capacity grew exponentially, states that ramped up later (like Rajasthan) added massive volumes, thereby reducing the relative percentage share of early pioneers, even if the pioneers continued to grow.'
      }
    ]
  },
  '/innovation': {
    title: 'Innovation Hub',
    greeting: 'Welcome to the lab! Need help with the AR Simulator?',
    questions: [
      {
        q: 'How does the AR Simulator work?',
        a: 'The AR Simulator requests your camera and runs a mathematical detection model. Once you click "Detect Surface", it calculates the square footage of the visible area and translates it into the maximum number of solar panels (at 45 sq ft per panel) that can fit!'
      },

      {
        q: 'Is the panel size calculation customizable?',
        a: 'Currently, the AR simulator defaults to a standard 45 sq ft panel for quick estimation. Future updates may allow users to input custom panel dimensions.'
      }
    ]
  },
  '/revenue': {
    title: 'Revenue Dashboard',
    greeting: 'Hello! I can explain the financial tracking mechanisms here.',
    questions: [
      {
        q: 'How is this different from the Executive Dashboard?',
        a: 'The Executive Dashboard focuses on physical Capacity (kW). This dashboard isolates the financial CapEx (Revenue in Crores). It helps stakeholders track investment velocity rather than just hardware installation.'
      },
      {
        q: 'What is CapEx in this context?',
        a: 'CapEx (Capital Expenditure) refers to the estimated total investment required to build the existing solar infrastructure, calculated based on the installed capacity and average market installation costs.'
      }
    ]
  },
  'default': {
    title: 'SolarIntel Assistant',
    greeting: 'Hello! How can I help you navigate the platform today?',
    questions: [
      {
        q: 'What is SolarIntel?',
        a: 'SolarIntel is a comprehensive AI-Based Solar Sales Analysis and Demand Forecasting System. It processes 10 years of macro data to provide actionable business intelligence.'
      },
      {
        q: 'Can you summarize all the pages available?',
        a: 'Certainly! 1) Executive Dashboard: High-level overview of capacity & revenue. 2) Detailed Analytics: Deep-dive into CAGR and YoY growth by State/City. 3) Geo Analytics: Interactive map and heatmaps. 4) ML Forecasting: AI-based future capacity predictions. 5) Sales Intelligence: Market share dynamics. 6) Innovation Hub: AR Simulator. 7) Revenue Dashboard: Financial tracking of capital expenditure.'
      },
      {
        q: 'How do I navigate between modules?',
        a: 'You can use the sidebar on the left to switch between different modules like Analytics, Geo-Mapping, Forecasting, and the Innovation Hub.'
      }
    ]
  }
};

const Chatbot = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [isTyping, setIsTyping] = useState(false);
  const location = useLocation();
  const messagesEndRef = useRef(null);

  // Get context based on current route
  const currentContext = pageContexts[location.pathname] || pageContexts['default'];

  // Reset chat when route changes
  useEffect(() => {
    setMessages([
      { type: 'bot', text: currentContext.greeting }
    ]);
  }, [location.pathname]);

  // Auto-scroll
  useEffect(() => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, isTyping]);

  const handleQuestionClick = (qaPair) => {
    // Add user question
    setMessages(prev => [...prev, { type: 'user', text: qaPair.q }]);
    setIsTyping(true);

    // Simulate network delay for realistic feel
    setTimeout(() => {
      setIsTyping(false);
      setMessages(prev => [...prev, { type: 'bot', text: qaPair.a }]);
    }, 800);
  };

  return (
    <>
      {/* Floating Action Button */}
      <button
        onClick={() => setIsOpen(true)}
        className={`fixed bottom-6 right-6 p-4 rounded-full bg-solar text-white shadow-2xl hover:scale-110 transition-transform duration-300 z-50 flex items-center justify-center ${isOpen ? 'scale-0 opacity-0' : 'scale-100 opacity-100'}`}
      >
        <MessageSquare className="w-6 h-6" />
      </button>

      {/* Chat Window */}
      <div 
        className={`fixed bottom-6 right-6 w-[380px] h-[600px] max-h-[80vh] bg-dark-950 border border-dark-800 rounded-3xl shadow-2xl flex flex-col overflow-hidden transition-all duration-300 z-50 transform origin-bottom-right ${isOpen ? 'scale-100 opacity-100' : 'scale-0 opacity-0 pointer-events-none'}`}
      >
        {/* Header */}
        <div className="bg-dark-900 border-b border-dark-800 p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-solar/20 flex items-center justify-center text-solar">
              <Bot className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-white leading-tight">{currentContext.title} AI</h3>
              <p className="text-xs text-green-400 font-medium flex items-center gap-1">
                <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse"></span>
                Online
              </p>
            </div>
          </div>
          <button 
            onClick={() => setIsOpen(false)}
            className="p-2 text-dark-400 hover:text-white hover:bg-dark-800 rounded-full transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Chat Area */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {messages.map((msg, idx) => (
            <div key={idx} className={`flex ${msg.type === 'user' ? 'justify-end' : 'justify-start'} animate-in fade-in slide-in-from-bottom-2 duration-300`}>
              <div className={`max-w-[85%] rounded-2xl p-3.5 text-sm leading-relaxed ${
                msg.type === 'user' 
                  ? 'bg-solar text-white rounded-tr-sm' 
                  : 'bg-dark-800 text-dark-100 rounded-tl-sm'
              }`}>
                {msg.text}
              </div>
            </div>
          ))}
          
          {isTyping && (
            <div className="flex justify-start animate-in fade-in">
              <div className="bg-dark-800 text-dark-400 rounded-2xl rounded-tl-sm p-3.5 flex gap-1">
                <div className="w-1.5 h-1.5 rounded-full bg-dark-400 animate-bounce" style={{ animationDelay: '0ms' }}></div>
                <div className="w-1.5 h-1.5 rounded-full bg-dark-400 animate-bounce" style={{ animationDelay: '150ms' }}></div>
                <div className="w-1.5 h-1.5 rounded-full bg-dark-400 animate-bounce" style={{ animationDelay: '300ms' }}></div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Interactive Question Chips */}
        <div className="p-4 bg-dark-900 border-t border-dark-800">
          <p className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-3 px-1">Suggested Questions</p>
          <div className="flex flex-col gap-2">
            {currentContext.questions.map((qa, idx) => (
              <button
                key={idx}
                onClick={() => handleQuestionClick(qa)}
                disabled={isTyping}
                className="text-left px-4 py-2.5 bg-dark-950 border border-dark-800 hover:border-solar hover:text-solar text-sm text-dark-300 rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed group"
              >
                <div className="flex items-start gap-2">
                  <MessageSquare className="w-4 h-4 mt-0.5 opacity-50 group-hover:opacity-100 flex-shrink-0" />
                  <span className="leading-snug">{qa.q}</span>
                </div>
              </button>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export default Chatbot;
